# FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
# WORKDIR /src

# COPY ./fin-api.csproj .
# RUN dotnet restore

# COPY . .
# RUN dotnet publish -c Release -o /app/publish --no-restore

# FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
# WORKDIR /app

# COPY --from=build /app/publish .

# ENV ASPNETCORE_ENVIRONMENT=Production

# EXPOSE 8080

# ENTRYPOINT ["dotnet", "fin-api.dll"]

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY ./Src/Fin.API/Fin.API.csproj ./Src/Fin.API/

RUN dotnet restore ./Src/Fin.API/Fin.API.csproj

COPY . .

RUN dotnet publish ./Src/Fin.API/Fin.API.csproj \
    -c Release \
    -o /app/publish \
    --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
WORKDIR /app

COPY --from=build /app/publish .

ENV ASPNETCORE_ENVIRONMENT=Production

EXPOSE 8080

ENTRYPOINT ["dotnet", "Fin.Api.dll"]