# FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
# WORKDIR /src

# COPY ./fin-api.csproj .
# RUN dotnet restore

# COPY . .
# RUN dotnet publish -c Release -o /app/publish --no-restore

# FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
# WORKDIR /app

# COPY --from=build /app/publish .

# ENV ASPNETCORE_ENVIRONMENT=Production

# EXPOSE 8080

# ENTRYPOINT ["dotnet", "fin-api.dll"]

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS api-build
WORKDIR /src

COPY fin-api.sln ./
COPY Src/ ./Src/

RUN dotnet restore Src/Fin.API/Fin.API.csproj
RUN dotnet publish Src/Fin.API/Fin.API.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
WORKDIR /app

COPY --from=api-build /app/publish .

ENV ASPNETCORE_ENVIRONMENT=Production
ENV ASPNETCORE_URLS=http://+:8080

EXPOSE 8080

ENTRYPOINT ["dotnet", "Fin.Api.dll"]