// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using fin_api.Data;

#nullable disable

namespace fin_api.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    partial class ApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("fin_api.Models.Categoria", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CorId")
                        .HasColumnType("text");

                    b.Property<string>("IconId")
                        .HasColumnType("text");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CorId");

                    b.HasIndex("IconId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("fin_api.Models.Cor", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cor");
                });

            modelBuilder.Entity("fin_api.Models.CorCategoriaUsuario", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("CategoriaId")
                        .HasColumnType("text");

                    b.Property<string>("CorId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "CategoriaId", "CorId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CorId");

                    b.ToTable("CorCategoriaUsuarios");
                });

            modelBuilder.Entity("fin_api.Models.Icon", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Icon");
                });

            modelBuilder.Entity("fin_api.Models.IconeCategoriaUsuario", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("CategoriaId")
                        .HasColumnType("text");

                    b.Property<string>("IconId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "CategoriaId", "IconId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("IconId");

                    b.ToTable("IconeCategoriaUsuarios");
                });

            modelBuilder.Entity("fin_api.Models.Transacao", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CategoriaId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataMovimentacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("boolean");

                    b.Property<int?>("ParcelaAtual")
                        .HasColumnType("integer");

                    b.Property<int?>("Parcelas")
                        .HasColumnType("integer");

                    b.Property<string>("ParentTransactionId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RecorrenciaEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RecorrenciaType")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("text");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ParentTransactionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("fin_api.Models.UserHiddenCategory", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("CategoryId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("UserHiddenCategories");
                });

            modelBuilder.Entity("fin_api.Models.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("fin_api.Models.Categoria", b =>
                {
                    b.HasOne("fin_api.Models.Cor", "CorPadrao")
                        .WithMany("Categorias")
                        .HasForeignKey("CorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("fin_api.Models.Icon", "IconePadrao")
                        .WithMany("Categorias")
                        .HasForeignKey("IconId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CorPadrao");

                    b.Navigation("IconePadrao");
                });

            modelBuilder.Entity("fin_api.Models.CorCategoriaUsuario", b =>
                {
                    b.HasOne("fin_api.Models.Categoria", "Categoria")
                        .WithMany("CorCategoriaUsuarios")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("fin_api.Models.Cor", "Cor")
                        .WithMany()
                        .HasForeignKey("CorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("fin_api.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Cor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("fin_api.Models.IconeCategoriaUsuario", b =>
                {
                    b.HasOne("fin_api.Models.Categoria", "Categoria")
                        .WithMany("IconeCategoriaUsuario")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("fin_api.Models.Icon", "Icone")
                        .WithMany()
                        .HasForeignKey("IconId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("fin_api.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Icone");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("fin_api.Models.Transacao", b =>
                {
                    b.HasOne("fin_api.Models.Categoria", "Categoria")
                        .WithMany("Transacoes")
                        .HasForeignKey("CategoriaId");

                    b.HasOne("fin_api.Models.Transacao", "ParentTransaction")
                        .WithMany()
                        .HasForeignKey("ParentTransactionId");

                    b.HasOne("fin_api.Models.Usuario", null)
                        .WithMany("transacaos")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Categoria");

                    b.Navigation("ParentTransaction");
                });

            modelBuilder.Entity("fin_api.Models.UserHiddenCategory", b =>
                {
                    b.HasOne("fin_api.Models.Categoria", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("fin_api.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("fin_api.Models.Categoria", b =>
                {
                    b.Navigation("CorCategoriaUsuarios");

                    b.Navigation("IconeCategoriaUsuario");

                    b.Navigation("Transacoes");
                });

            modelBuilder.Entity("fin_api.Models.Cor", b =>
                {
                    b.Navigation("Categorias");
                });

            modelBuilder.Entity("fin_api.Models.Icon", b =>
                {
                    b.Navigation("Categorias");
                });

            modelBuilder.Entity("fin_api.Models.Usuario", b =>
                {
                    b.Navigation("transacaos");
                });
#pragma warning restore 612, 618
        }
    }
}
